name: Docker Base Image CI (XangCastle)

on:
  push:
    branches:
      - master
    paths:
      - 'docker/images/n8n-base/Dockerfile'
  pull_request:
    paths:
      - 'docker/images/n8n-base/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ '20', '22', '24' ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./docker/images/n8n-base/Dockerfile
          build-args: |
            NODE_VERSION=${{ matrix.node_version }}
          platforms: linux/amd64,linux/arm64
          provenance: ${{ github.event_name == 'push' }}
          sbom: ${{ github.event_name == 'push' }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            xangcastle/n8n-base:${{ matrix.node_version }}-${{ github.sha }}
            xangcastle/n8n-base:${{ matrix.node_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
